In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix

In [2]:
df = pd.read_csv("../data/training-data.csv")
df.head()

   user_id  trip_id  rating
0        1        1       5
1        1        2       4
2        1        5       2
3        2        1       3
4        2        3       5

In [3]:
user_item_matrix = df.pivot_table(
    index='user_id',
    columns='trip_id',
    values='rating'
).fillna(0)

user_item_matrix

trip_id    1    2    3    4    5    6
user_id
1        5.0  4.0  0.0  0.0  2.0  0.0
2        3.0  0.0  5.0  4.0  0.0  0.0
3        0.0  5.0  4.0  0.0  0.0  5.0
4        0.0  0.0  0.0  2.0  4.0  5.0
5        4.0  0.0  2.0  0.0  0.0  5.0

In [4]:
matrix = csr_matrix(user_item_matrix.values)

In [5]:
svd = TruncatedSVD(n_components=2)
latent_matrix = svd.fit_transform(matrix)

latent_matrix

array([[ 3.97826179, -2.74364312],
       [ 4.29740351, -4.33799411],
       [ 6.87661104,  1.7188714 ],
       [ 4.32148945,  3.7233714 ],
       [ 5.75798729,  0.28595433]])

In [6]:
import pickle

with open("../models/svd_model.pkl", "wb") as f:
    pickle.dump(svd, f)

In [7]:
import numpy as np

# Choose a user
user_id = 1

# Get user vector
user_vector = latent_matrix[user_id - 1]

# Calculate scores for all trips
scores = user_vector.dot(svd.components_)

# Sort trips by score
recommended_trip_indices = np.argsort(scores)[::-1]

print("Recommended Trip IDs:")
print(recommended_trip_indices + 1)  # +1 because trip IDs start from 1

Recommended Trip IDs:
[1 3 2 4 6 5]